CREATE DATABASE QUANLYKHACHSAN
GO

DROP TABLE IF EXISTS TAI_KHOAN
GO

CREATE TABLE TAI_KHOAN (
	ID INT NOT NULL IDENTITY,
	USERNAME NVARCHAR(255) NOT NULL,
	PASSWORD NVARCHAR(255) NOT NULL,
	ROLE NVARCHAR(255) NOT NULL
);
GO

ALTER TABLE TAI_KHOAN ADD CONSTRAINT PK_TAI_KHOAN PRIMARY KEY (ID);
GO

INSERT INTO TAI_KHOAN (USERNAME, PASSWORD, ROLE) VALUES ('bellman1', '123', N'Bellman');
INSERT INTO TAI_KHOAN (USERNAME, PASSWORD, ROLE) VALUES ('bellman2', '123', N'Bellman');
INSERT INTO TAI_KHOAN (USERNAME, PASSWORD, ROLE) VALUES ('bellman3', '123', N'Bellman');
INSERT INTO TAI_KHOAN (USERNAME, PASSWORD, ROLE) VALUES ('khachhang1', '123', N'Khách hàng');
INSERT INTO TAI_KHOAN (USERNAME, PASSWORD, ROLE) VALUES ('khachhang2', '123', N'Khách hàng');
INSERT INTO TAI_KHOAN (USERNAME, PASSWORD, ROLE) VALUES ('khachhang3', '123', N'Khách hàng');
INSERT INTO TAI_KHOAN (USERNAME, PASSWORD, ROLE) VALUES ('letan1', '123', N'Lễ tân');
INSERT INTO TAI_KHOAN (USERNAME, PASSWORD, ROLE) VALUES ('letan2', '123', N'Lễ tân');
INSERT INTO TAI_KHOAN (USERNAME, PASSWORD, ROLE) VALUES ('letan3', '123', N'Lễ tân');

DROP TABLE IF EXISTS THONG_TIN_KHACH_HANG
GO

CREATE TABLE THONG_TIN_KHACH_HANG (
	MAKHACHHANG INT NOT NULL,
	HOTEN NVARCHAR(255) NOT NULL,
	DIACHI NVARCHAR(255) NOT NULL,
	CCCD BIGINT NOT NULL,
	SDT BIGINT NOT NULL
);
GO

ALTER TABLE THONG_TIN_KHACH_HANG ADD CONSTRAINT PK_THONG_TIN_KHACH_HANG PRIMARY KEY (MAKHACHHANG);
GO

INSERT INTO THONG_TIN_KHACH_HANG (MAKHACHHANG, HOTEN, DIACHI, CCCD, SDT) VALUES (4, N'Lê Minh Trí', N'TP Hồ Chí Minh', 078223051256  ,0933491044);
INSERT INTO THONG_TIN_KHACH_HANG (MAKHACHHANG, HOTEN, DIACHI, CCCD, SDT) VALUES (5, N'Nguyễn Lê Hải Đăng', N'TP Hà Nội', 029302511692  ,0934591051);
INSERT INTO THONG_TIN_KHACH_HANG (MAKHACHHANG, HOTEN, DIACHI, CCCD, SDT) VALUES (6, N'Trần Minh Triết', N'TP Đà nẵng', 045206091294  ,0931791142);
GO

DROP TABLE IF EXISTS THONG_TIN_KHACH_DOAN
GO

CREATE TABLE THONG_TIN_KHACH_DOAN (
	MADOAN INT NOT NULL,
	TENDOAN NVARCHAR(255) NOT NULL,
	SOFAX BIGINT NOT NULL,
	SOLUONG INT NOT NULL
);

ALTER TABLE THONG_TIN_KHACH_DOAN ADD CONSTRAINT PK_THONG_TIN_KHACH_DOAN PRIMARY KEY (MADOAN);
GO

INSERT INTO THONG_TIN_KHACH_DOAN (MADOAN, TENDOAN, SOFAX, SOLUONG) VALUES (1, N'Đoàn du lịch Vintour', 0399452046, 1);
INSERT INTO THONG_TIN_KHACH_DOAN (MADOAN, TENDOAN, SOFAX, SOLUONG) VALUES (2, N'Đoàn du lịch Suntour', 0399514652, 2);

DROP TABLE IF EXISTS CHI_TIET_KHACH_DOAN
GO

CREATE TABLE CHI_TIET_KHACH_DOAN (
	MAKHACHHANG INT NOT NULL,
	MADOAN INT NOT NULL
);
GO

ALTER TABLE CHI_TIET_KHACH_DOAN ADD CONSTRAINT PK_CHI_TIET_KHACH_DOAN PRIMARY KEY (MAKHACHHANG, MADOAN);
GO

INSERT INTO CHI_TIET_KHACH_DOAN (MAKHACHHANG, MADOAN) VALUES (4, 1);
INSERT INTO CHI_TIET_KHACH_DOAN (MAKHACHHANG, MADOAN) VALUES (5, 2);
INSERT INTO CHI_TIET_KHACH_DOAN (MAKHACHHANG, MADOAN) VALUES (6, 2);

DROP TABLE IF EXISTS THONG_TIN_PHONG_KHACH_SAN
GO

CREATE TABLE THONG_TIN_PHONG_KHACH_SAN (
	MAPHONG INT NOT NULL IDENTITY,
	NGAYTHUE DATE,
	NGAYTRA DATE,
	TINHTRANG NVARCHAR(255) NOT NULL,
	LOAI NVARCHAR(255) NOT NULL
);
GO

ALTER TABLE THONG_TIN_PHONG_KHACH_SAN ADD CONSTRAINT PK_THONG_TIN_PHONG_KHACH_SAN PRIMARY KEY (MAPHONG);
GO

INSERT INTO THONG_TIN_PHONG_KHACH_SAN (TINHTRANG, LOAI) VALUES (N'Trống', N'Thường');
INSERT INTO THONG_TIN_PHONG_KHACH_SAN (TINHTRANG, LOAI) VALUES (N'Trống', N'Thường');
INSERT INTO THONG_TIN_PHONG_KHACH_SAN (TINHTRANG, LOAI) VALUES (N'Trống', N'Vip');
INSERT INTO THONG_TIN_PHONG_KHACH_SAN (TINHTRANG, LOAI) VALUES (N'Trống', N'Vip');
INSERT INTO THONG_TIN_PHONG_KHACH_SAN (TINHTRANG, LOAI) VALUES (N'Trống', N'Vip');

DROP TABLE IF EXISTS THONG_TIN_DAT_PHONG
GO

CREATE TABLE THONG_TIN_DAT_PHONG (
	MADATPHONG INT NOT NULL IDENTITY,
	MAPHONG INT NOT NULL,
	MAKHACHHANG INT NOT NULL,
	MANHANVIEN INT NOT NULL,
	NGAYDAT DATE NOT NULL,
	NGAYCHECKIN DATE NOT NULL,
	NGAYCHECKOUT DATE NOT NULL
);
GO

ALTER TABLE THONG_TIN_DAT_PHONG ADD CONSTRAINT PK_THONG_TIN_DAT_PHONG PRIMARY KEY (MADATPHONG);
GO

INSERT INTO THONG_TIN_DAT_PHONG (MAPHONG, MAKHACHHANG, MANHANVIEN, NGAYDAT, NGAYCHECKIN, NGAYCHECKOUT) VALUES (3, 5, 7, '2023-5-26', '2023-6-2', '2023-6-4');
GO
UPDATE THONG_TIN_PHONG_KHACH_SAN SET TINHTRANG = N'Hết' WHERE MAPHONG = 3;

